AWSTemplateFormatVersion: 2010-09-09
Resources:
  WeatherFunction:
    Type: 'AWS::Lambda::Function'
    Properties: {}
  WeatherSite:
    Type: 'AWS::S3::Bucket'
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
Parameters:
  IndexFileParam:
    Type: String
    Description: Enter your openweathermap.org API key here.
    Default: index.html
    
